### ISSUE TITLE
api の訳

### ISSUE THREAD

**Issue by ytklod** [okfj/opendatahandbook-v2#2]
初めて issue を発行します。使い方を間違っていたらご指摘下さい。

第二文目の補語は、「"for ..." が "to ..." するための、"provided by ..." された "way (方法、手段)"」という構造だと思います。

https://github.com/okfj/opendatahandbook-v2/blob/gh-pages/glossary/ja/terms/api/index.md

**Comment by higa4** [comment]
ご指摘ありがとうございます。issueの使い方はこんな感じでお気づきの点を残して頂ければ大丈夫です。現時点ではみなさまに下訳として進捗を優先して頂いているので、レビューのフェーズになりましたら参考にさせて頂きながらブラッシュアップして行きたいと思います。当初は明日からレビューの予定だったのですがちょっと厳しいかもですね。

**Comment by higa4** [comment]
いったんクローズします。
