### ISSUE TITLE
citizen-engagement の訳

### ISSUE THREAD

**Issue by ytklod** [okfj/opendatahandbook-v2#3]
「参加させる」の響きが、強制的とか、上から目線という印象を少し受けます。かといって「参加してもらう」では下手に出ています。すみませんが、今のところ代案は思い付いていないです。

https://github.com/okfj/opendatahandbook-v2/blob/gh-pages/glossary/en/terms/citizen-engagement/index.md

**Comment by higa4** [comment]
いったんクローズします。
