### ISSUE TITLE
作業進行について

### ISSUE THREAD

**Issue by higa4** [okfj/opendatahandbook-v2#4]
こちらで全体の進行につきまして作業にご参加頂いているみなさまにアナウンスさせて頂きますのでよろしくお願いします。

当初予定では本日5/18にレビュー済みの初版について本家にPRを出してマージしてもらう予定だったのですが、やや作業がズレ込んでいますので明日5/19お昼頃にいったん下訳を締めて、ドラフト版として明日中にPRを出すことにします。それまで、残分（更新時のコメント欄が初期ロード時の「fix header to ja」のままとなっているもの）の下訳にご協力頂ける方は引き続きお願いいたします。（5/18 23:40時点での下訳の進捗は124件中、107件完了です）
まだ十分なレビューができていない状態ですが、ひとまず何も無いよりもドラフト版を出すことを優先いたします。
その後の進め方はまた改めてお知らせさせて頂きます。まだ早いですが、ここまで翻訳にご協力頂いたみなさまに感謝いたします。

**Comment by ytklod** [comment]
すみませんが、bandwidth と saas は訳そうと思って一旦編集中にしたもののあきらめましたので、進捗しているように見えますが、未翻訳状態です。

https://github.com/okfj/opendatahandbook-v2/blob/gh-pages/glossary/ja/terms/bandwidth/index.md
https://github.com/okfj/opendatahandbook-v2/tree/gh-pages/glossary/ja/terms/saas/index.md

また、de-identification も途中の文の構造が分からなかったので、途中であきらめました。

https://github.com/okfj/opendatahandbook-v2/blob/gh-pages/glossary/ja/terms/de-identification/index.md

以上 3 件も、どなたか代わりに作業していただければ幸いです。お手数ですがよろしくお願い致します。

**Comment by higa4** [comment]
状況のお知らせありがとうございます。大変助かります。承知いたしました。

**Comment by higa4** [comment]
みなさま、PRがマージされ、Website上で公開されました。ご協力ありがとうございました。
http://opendatahandbook.org/glossary/ja/
（用語の順番がソートされていないのはバグでいずれ修正されるそうです）

Website上での表示を確認した結果、用語の数が多く、このままでは（ソートされたとしても）用語を探すのが大変そうに思われるため、やはり見出しは日本語に変えることにします。
つきましては引き続き作業に協力頂ける方がおられましたら下記要領にて修正のご支援をお願いします。（先頭の10件ほどは修正済み）

１．見出しの日本語化
・用語の見出し(title)は原則日本語とする。（その際、元の英語は本文の先頭に移動）
・適切な訳語が無いもの（例：SQL）は英語を半角のまま使用する。
・本文中の他用語へのリンク部分も見出しに合わせる。その際、[]や()の前後に半角スペースが入っているものは削除する。
・具体的な見出しの値は下記B列を参照
https://docs.google.com/spreadsheets/d/1LGbs_DF70oPXtOqBR_xgPEWEXrvi0iG7pMPMLZ9S9yI/edit#gid=0

２．原文への追従
・英語の原文が一部更新されているため、上記１．の作業を行う際、下記原文と見比べながら変わっている部分があれば更新する。
https://github.com/okfn/opendatahandbook/tree/d09bbc769da83af5acfd37bcb039f39f3b2881c9/glossary/en/terms
・ざっと見たところ{}が削除されていたり、他用語へのリンクに修正されている場合が多いようです。おそらく{}は用語として別途登録しようとしていたけどやっぱりやめた、という感じです。

３．未翻訳用語の翻訳
・未訳のものが２，３残っていますので引き続きお願いします。

**Comment by higa4** [comment]
用語のソート順や別用語へのリンク部分など、一部不具合が残っていますが、一通りの翻訳が終わり、ウェブサイトに掲載されました。
http://opendatahandbook.org/glossary/ja/
みなさまのご協力に感謝申し上げます。

一般公開（告知）は今のところもうしばらく様子を見て不具合修正が終わってからにしたいと考えています。
なお、気になる点などありましたら引き続き直接修正して頂いて構いません。

**Comment by higa4** [comment]
みなさま、たいへん遅くなりましたが用語のソート順がちゃんと並ぶようになりましたので一般に告知させて頂きます。ご協力ありがとうございました。
http://opendatahandbook.org/glossary/ja/
