### ISSUE TITLE
Open Governmentの訳

### ISSUE THREAD

**Issue by aalt** [okfj/opendatahandbook-v2#5]
responsive や due process といった辺り諸々がちょいと気になったので、訳案を書いてみました。

https://github.com/okfj/opendatahandbook-v2/blob/gh-pages/glossary/ja/terms/open-government/index.md

Open government。オープン・ガバメントは、一般的に[オープン運動](/glossary/en/terms/open-movement/)に即して、市民にとって透明で、市民への説明可能で、市民へ責任を全うする、政府の仕組みづくりを目指している。これは民主主義の理念、適正な手続き、市民参画、そしてガバメント情報の開示を含む。ガバメント情報の開示への徹底的で継続的なアプローチは、たとえば、立法や予算について草案作成や校正などにおける、市民参画の実現を目指している。[OGP](/glossary/ja/terms/ogp/)参照。

**Comment by higa4** [comment]
ご指摘ありがとうございます。反映させました。本家への次のプルリクエストにも入れておきます。
